# Generated by Django 3.0.2 on 2020-02-20 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gameapi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='creator',
        ),
    ]
