# Generated by Django 3.0.2 on 2020-02-20 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameapi', '0005_auto_20200220_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
